# User schema

# --- !Ups
ALTER TABLE `artist_attribute` DROP PRIMARY KEY, MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE `event_attribute` DROP PRIMARY KEY, MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE `event_artist` DROP PRIMARY KEY, MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

# --- !Downs
ALTER TABLE `artist_attribute` DROP PRIMARY KEY, MODIFY COLUMN id INT UNSIGNED NOT NULL PRIMARY KEY FIRST;
ALTER TABLE `event_attribute` DROP PRIMARY KEY, MODIFY COLUMN id INT UNSIGNED NOT NULL PRIMARY KEY FIRST;
ALTER TABLE `event_artist` DROP PRIMARY KEY, MODIFY COLUMN id INT UNSIGNED NOT NULL PRIMARY KEY FIRST;

